spring.application.name=ventas_sb
spring.datasource.url=jdbc:mysql://localhost:3306/ventas
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=root

spring.sql.init.data-locations=classpath*:db/data.sql
spring.sql.init.schema-locations=classpath*:db/schema.sql
spring.sql.init.mode=always

logging.level.root = info
logging.level.org.iesvdm.ventas_sb.dao = debug
